### ISSUE TITLE
Adding custom driver

### ISSUE THREAD

**Issue by sanderha** [thephpleague/omnipay-example#8]
Hey, I wrote an unsupport driver for Omnipay. Is it possible to test it with omnipay-example aswell?

**Comment by judgej** [comment]
For now at least, you will need to add it to the gateways list in [omnipay-common composer.json](https://github.com/thephpleague/omnipay-common/blob/master/composer.json)

Just hack it in, or fork omnipay-common. Not ideal, I know, but this example app is just used for development.

**Comment by sanderha** [comment]
I see. Thanks!
