### ISSUE TITLE
When running with php -S the client IP sent to the gateway is invalid

### ISSUE THREAD

**Issue by dmnc** [thephpleague/omnipay-example#9]
`$app['request']->getClientIp()` returns `::1`.

In the SagePay gateway at least, this causes a failure.

**Comment by judgej** [comment]
I think Silex/Symfony has a `isValidPublicIP($ip)` method on the request object that can be used to check whether the supplied IP is valid or not, before trying to pass it to the gateway.

**Comment by delatbabel** [comment]
> $app['request']->getClientIp() returns ::1.

Which is a valid IPv6 address.

> In the SagePay gateway at least, this causes a failure.

Which is a bug with sagepay and should be raised with them.

If it's known that the gateway requires a valid public IP address then as @judgej suggests, call isValidPublicIP(). However this may not be valid for token payments, etc.

**Comment by judgej** [comment]
I am not sure it needs to be a public IP address, but it does need to be a V4 IP address.

The validation is up 15 characters, with `0`-`9` and `.` only allowed.

**Comment by delatbabel** [comment]
> I am not sure it needs to be a public IP address (so 127.0.0.1 may be allowed - not tried it yet), but it does need to be a V4 IP address.

Yes, for SagePay. I'm aware of at least 3 other gateways that support IPv6.

This code should go into SagePay and not any generic omnipay code.

Leaving this closed for now.
